apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch"
  labels:
    component: "elasticsearch"
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    component: "elasticsearch"
    type: "client"
  type: "LoadBalancer"
