apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch-masters"
  labels:
    component: "elasticsearch"
    type: "master"
spec:
  clusterIP: "None"
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    type: "master"
    component: "elasticsearch"
