apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "elasticsearch-node"
  labels:
    component: "elasticsearch"
    type: "node"
spec:
  replicas: 3
  selector:
    component: "elasticsearch"
    type: "node"
  template:
    metadata:
      labels:
        component: "elasticsearch"
        type: "node"
    spec:
      serviceAccount: elasticsearch
      serviceAccountName: elasticsearch
      containers:
        - env:
            - name: "SERVICE"
              value: "elasticsearch-cluster"
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "caicloud/elasticsearch:2.1.0"
          name: "elasticsearch"
          ports:
            - containerPort: 9300
              name: "transport"
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: "elasticsearch-data"
              readOnly: false
      volumes:
        - emptyDir:
            medium: ""
          name: "elasticsearch-data"
